PR template updated
usagov/usagov-2021 pull request #1181
Opened 2023-09-19 15:09 UTC by YaritzaGarcia

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1146

## Description

Update the current PR template based on the [PR Template Brainstorm](https://docs.google.com/document/d/1dj0PptulgFOzihwEM9DQr7PC_oaqYyXUVJ9f8-VyuhM/edit#heading=h.s1w6hh4mcjsb).

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2023-09-19 16:51 UTC, IsabelLaurenceau requested changes
So far so good, I only have a few requests. 
I think 
### Requires New Content/Config
- [ ] Yes
- [ ] No
 
should be two separate checkbox items since they are rectified differently i.e 
### Requires New Config
- [ ] Yes
- [ ] No

### Requires New Content
- [ ] Yes
- [ ] No

For the Post PR Approval Instructions since there are multiple ways to approve on CircleCi I would just keep instructions 1 & 2 and aded a 3rd that says "build and deploy." Also keeps it shorter so less likely to be skipped over. 

Also just want to mention the comments don't come up in the markdown. It looks like you kinda want them too based on how you wrote them so maybe just change the ones you want to appear to normal text. You can italicizes them to show it's like "instructions for the section"

2023-09-19 16:55 UTC, jacobaaronyeager requested changes
Looks amazing!  A couple small changes, let me know when you push and I'll approve :)

2023-09-19 16:55 UTC, jacobaaronyeager commented on .github/pull_request_template.md
> +<!-- This instructions are d ifferent from “testing instructions” in Jira – those are typically for Content/UX stakeholders -->
looks like there is an errant space in the word different: d ifferent

2023-09-19 16:55 UTC, jacobaaronyeager commented on .github/pull_request_template.md
> +6. Press the thumbs up icon, which appears next to "approve-dev-deployment", to deploy the changes to dev. Once the deployment to cloudgov-dev is complete, [cms-dev.usa.gov](http://cms-dev.usa.gov/)
Extra "They" in the last clause: the changes **They** will be made visible

2023-09-19 16:59 UTC, akf requested changes
Thanks! I proofread and made a couple of suggestions.

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +  - Add a screenshot on how it should look like
Text tweak: "Add screenshot showing what it should look like"

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +<!-- This instructions are d ifferent from “testing instructions” in Jira – those are typically for Content/UX stakeholders -->
Remove stray space in "d ifferent"

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +- [ ] Test instruction 1
These should probably just be bullets, not checkboxes.

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +- [ ] Chnges permissions or workflow
Chnges -> Changes

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +6. Press the thumbs up icon, which appears next to "approve-dev-deployment", to deploy the changes to dev. Once the deployment to cloudgov-dev is complete, [cms-dev.usa.gov](http://cms-dev.usa.gov/)
remove word "They".

2023-09-19 16:59 UTC, akf commented on .github/pull_request_template.md
> +6. Press the thumbs up icon, which appears next to "approve-dev-deployment", to deploy the changes to dev. Once the deployment to cloudgov-dev is complete, [cms-dev.usa.gov](http://cms-dev.usa.gov/)
Let's add a final instruction to update the Jira ticket. My suggestion: 

7. Update the Jira ticket: change the status of the ticket to *Review in Test* and add a comment. State whether the change is already visible on  [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2023-09-19 18:59 UTC, akf approved these changes

2023-09-21 18:05 UTC, jacobaaronyeager approved these changes

2023-09-21 20:39 UTC, IsabelLaurenceau approved these changes

2023-09-21 20:39 UTC, merged