901 adding header html field in life event
usagov/usagov-2021 pull request #1422
Opened 2024-02-15 00:29 UTC by gchi25

…eld-in-life-event: add header html field in life event

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-

## Description

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

### Requires New Config
- [ ] Yes
- [ ] No

### Requires New Content
- [ ] Yes
- [ ] No

### Validation Steps
- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-02-15 20:54 UTC, IsabelLaurenceau commented
Getting an error when trying to do bin/drush cim
![Screenshot 2024-02-15 at 3 54 08 PM](https://github.com/usagov/usagov-2021/assets/108532577/be67383c-b392-49f6-8d9b-b580492726c0)

2024-02-15 20:57 UTC, IsabelLaurenceau requested changes
See config upload error above

2024-02-16 01:02 UTC, gchi25 commented
Added config/sync/field.field.node.bears_life_event.field_header_html.yml

2024-02-20 13:35 UTC, IsabelLaurenceau approved these changes

2024-02-20 13:38 UTC, merged