Usagov 1387 state and territory abbrv
usagov/usagov-2021 pull request #1463
Opened 2024-03-06 14:54 UTC by IsabelLaurenceau

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1387

## Description

Added abbreviation field so abbreviations could be used for drop down in states and territories search. 

## Type of Changes

- [x] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

### Requires New Config
- [x] Yes
- [ ] No

### Requires New Content
- [x] Yes
- [ ] No

### Validation Steps
- Import config
- Go to content and open a few state directory pages (in English and Spanish) to edit 
- Add abbreviations to those pages
- Go to /state-governments and /es/gobiernos-estatales
- On those pages in the drop down use the search as you type feature. Test that
-- typing the beginning of a state name returns the expected result
-- typing the abbreviation of a state (that you put an abbreviation in) returns the expected result 
-- typing the beginning of the second word of a state (i.e "Ri" for Puerto Rico) returns the expected result
-- typing the middle of a state name (i.e "aba" for Alabama) does not return that state 

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders
- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions
Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-03-09 02:02 UTC, akf requested changes
It works flawlessly. All I'm asking is that you clean up the lint errors on the stateDirectory.js file!

2024-03-09 02:02 UTC, akf commented on web/themes/custom/usagov/templates/field--node--field-custom-twig-content-elected-officials.html.twig
> +            {# For the data-filter =
Thanks for commenting this!

2024-03-09 02:02 UTC, akf commented on web/themes/custom/usagov/scripts/stateDirectory.js
The "lint" job is failing (commit workflow), and at first I was puzzled because it seemed to be complaining about files you haven't touched. Well, it is, but apparently it's treating those as just warnings. What it's actually complaining about are a few things in this file: 

```
   6:31  error  Expected '===' and instead saw '=='              eqeqeq
  40:26  error  Expected '===' and instead saw '=='              eqeqeq
  55:9   error  'stateValue' is assigned a value but never used  no-unused-vars
```
The `eqeqeq` rule looks reasonable: https://eslint.org/docs/latest/rules/eqeqeq

2024-03-11 16:29 UTC, IsabelLaurenceau commented on web/themes/custom/usagov/scripts/stateDirectory.js
Ah thank you! I could not figure out what it was complaining about. Fixed!

2024-03-11 16:59 UTC, akf approved these changes

2024-03-11 17:00 UTC, merged