USAGOV-1773-clear-menu-link:
usagov/usagov-2021 pull request #1923
Opened 2024-09-04 17:55 UTC by omerida

…ink cache.

 Needed when running a Tome export to build page navigation correctly when more than one path is exported by a process.

## Jira Task

 Adds an event subscriber to clear menu l…
https://cm-jira.usa.gov/browse/USAGOV-

## Description

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] Egress
  - [ ] Tools
- [ ] Other

## Testing Instructions

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-09-13 19:48 UTC, akf requested changes

2024-09-13 19:48 UTC, akf commented on scripts/tome-static.sh
> +time drush tome:static -y --uri=$URI --process-count=$TOME_PROCESS_COUNT --path-count=10
Let's drop this back down to 1. 
I've identified what I think is another Tome bug; many details are on the Jira ticket.

2024-09-13 19:48 UTC, akf commented on web/modules/custom/usagov_ssg_postprocessing/src/EventSubscriber/RequestPrepareSubscriber.php
> +    private MenuActiveTrailInterface $menu_active_trail,
Is this what you want to inherit from?

2024-09-27 01:19 UTC, akf commented
@omerida I'm just reviewing things and I think this PR should be marked "draft" until you think it's good to go. So I did that.

2024-10-09 23:00 UTC, akf commented
@omerida you say "html-tidy config attached" -- did you forget to attach it, or am I not looking in the right place?

2024-10-10 14:03 UTC, omerida commented
@akf I remember attaching it somewhere, not sure if here or Jira now and updating the same validation steps. I think that was a different ticket and I copied the updated validation steps over to here 

[tidy-config.txt](https://github.com/user-attachments/files/17329297/tidy-config.txt)

2024-10-10 15:51 UTC, omerida commented
I'm seeing odd differences now too. One thing I should have added above is to run `composer install` to patch tome

2024-10-10 17:14 UTC, akf commented
Yeah, I noticed that. We have bin/drupal-update which does that plus a bit more and I did that.

2024-10-10 21:15 UTC, omerida commented
I found another cache that should be busted, for menu link content. I've updated the RequestPrepareSubscriber to reset it. I'm testing it now and will push the update shortly (waiting for one more tome run to finish)

2024-10-10 23:06 UTC, akf commented
Glad to hear it! I realized today that I probably, um, moved the `html` folder _into_ an existing `html-dev` folder instead of renaming it as I'd intended, and that would account for a lot of the unexpected HTML changes was seeing. I realized I had nested folders yesterday when trying to figure out why the redirect count was so much higher in that folder, but I didn't make the connection with the other errors until today. 
I have been using the `mv` command for well over 30 years, btw.

2024-10-11 19:07 UTC, omerida commented
@akf Resetting the menu link content cache generates the same HTML but only if I run `drush cr` before I run the tome command. After the  first run, a handful of pages will have the wrong datalayer, or navigation cards. I'll keep digging to see what other menu related cache might be involved.

2024-10-11 21:16 UTC, omerida commented
I found another cache to reset and pushed an update to bust it. Multiple runs still eventually start showing the wrong breadcrumbs, menu, or navigation cards on occasion. I'm going to move this back to draft and keep testing

2024-10-18 21:22 UTC, omerida commented
Found there's a cache related issue with menu_breacrumb module that has a patch. I've updated with the patch locally and am not running into random taxonomy datalayer / breadcrumb / nav card page weirdness when running tome. I've pushed that update here. On Monday I will do some more testing and (hopefully) can switch this away from draft.

2024-10-21 20:34 UTC, omerida commented
OK, it looks like the 'menu' entity manager needs to have its cache cleared between requests via Tome's subscriber. I've tested exports and I'm not seeing the random datalayer or navigation card pages after sequential exports.

The process is 2x as fast with a path count of 10 versus 1. Going up to 20 didn't seem to make a big difference in my limited testing

With path count = 1:

```
real    13m 15.41s
user    38m 18.74s
sys     7m 12.38s
```

With path count = 10:

```
real    6m 10.38s
user    16m 12.63s
sys     1m 31.80s
```

I also spoke to Dale and his PR for wizard datalayer issues addresses the duplicated rows I was seeing in published pages.csv.

2024-10-21 21:13 UTC, omerida commented
Just found that the export static asset pass also needs to track init_paths to prevent exporting the same path multiple times. I need re-roll the patch and test some more.

2024-10-23 02:23 UTC, akf reviewed
I ran one test on my local and it passed everything in your description except (sorry, there's an "except") ... there is a difference in the mobile menus on the agency index "letter" pages. It's just the agency index pages, both English and Spanish. But it does seem to be all of the agency index pages (21 English, 15 Spanish). 

After doing the diff, I viewed my site as an anonymous user and I could see the incorrect menu, so I can give you a screen shot! 

Here's what the text diff looks like for a single page. 
```
diff -brwd --strip-trailing-cr --exclude=_data -I js-view-dom-id --exclude=themes tidy-html-dev/agency-index/b/index.html tidy-html-1773/agency-index/b/index.htm\
l                                                                                                                                                                 
17,43c17,43                                                                                                                                                       
---                                                                                                                                                               
171c171                                                                                                                                                           
< <li class="navigation__item">                                                                                                                                   
---                                                                                                                                                               
> <li class="navigation__item"><a href="/agency-index">A-Z index of U.S. government departments and agencies</a>                                                  
173,174d172                                                                                                                                                       
< <li class="navigation__item sibling"><a href="/buy-from-government">Buying from the U.S. government</a></li>                                                    
< <li class="navigation__item sibling"><a href="/facts-figures">U.S. facts and figures</a></li>                                                                   
176,181d173                                                                                                                                                       
< <li class="navigation__item sibling"><a href="/state-local-governments">State and local governments</a></li>                                                    
< <li class="navigation__item sibling"><a href="/branches-of-government">Branches of government</a></li>                                                          
< <li class="navigation__item sibling"><a href="/elected-officials">Elected officials</a></li>                                                                    
< <li class="navigation__item sibling"><a href="/laws-and-regulations">Federal laws and regulations</a></li>                                                      
< <li class="navigation__item sibling"><a href="/tribes">Indian tribes and resources for Native Americans</a></li>                                                
< <li class="navigation__item sibling"><a href="/courts">Federal, state, territory, county, and municipal courts</a></li>          
```

And here's a screen shot of a page showing what that looks like on a rendered (cms) page: 
![bad-a-z-mobile-menu](https://github.com/user-attachments/assets/5896b711-e02c-45b6-83b8-08d7362115bc)

2024-10-23 02:23 UTC, akf commented on web/modules/custom/usagov_ssg_postprocessing/src/EventSubscriber/TomeEventSubscriber.php
> +   * Prevent exporting paths Tome might discover after the collect paths event.
So, specifically "prevent exporting _node_-based paths" ... 

This is probably a separate can of worms, but I look at this simple function and wonder whether it might not be a better approach than what we currently have for excludeDirectories? That is, go ahead and let the all the paths be collected, and then mark the ones that match our exclusion rules as invalid?

2024-10-23 19:35 UTC, omerida commented
> I ran one test on my local and it passed everything in your description except (sorry, there's an "except") ... there is a difference in the mobile menus on the agency index "letter" pages. It's just the agency index pages, both English and Spanish. But it does seem to be all of the agency index pages (21 English, 15 Spanish).

We chatted about this in [Jira](https://cm-jira.usa.gov/browse/USAGOV-1937?focusedId=2054385&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2054385)

2024-10-23 19:40 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/EventSubscriber/TomeEventSubscriber.php
> +   * Prevent exporting paths Tome might discover after the collect paths event.
It might be somewhat faster if you don't have to load the node entities too, no? Though I bet those are cached already...

2024-10-23 20:13 UTC, akf commented on web/modules/custom/usagov_ssg_postprocessing/src/EventSubscriber/TomeEventSubscriber.php
> +   * Prevent exporting paths Tome might discover after the collect paths event.
I would expect it to be. I'm certain that when I wrote that, I didn't think there was a way to get at the path alias without loading the node entity.

2024-10-25 00:25 UTC, akf approved these changes
It all checks out. The only differences I found were those darn agency index mobile menus, which we've agreed are a separate problem.

2024-10-25 00:25 UTC, merged