USAGOV-1969 Manage search result weights
usagov/usagov-2021 pull request #2013
Opened 2024-10-16 19:43 UTC by omerida

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-1969

## Description

Installs the sortableviews module to provide a drag-and-drop UI for managing the weight field of search results.

## Type of Changes

- [x] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [x] Drupal Config (requires "drush cim")
- [x] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [ ] Other

## Testing Instructions

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- On English benefit finder page, should see a local task linking to the sorting view. 
 
![image](https://github.com/user-attachments/assets/c985cf3f-fce5-44e0-8d89-d1dc25060d72)

   - Clicking on the link should take you to the view for sorting English benefit pages. `/admin/manage-benefits-search-sort/en`

![image](https://github.com/user-attachments/assets/b5f200b3-3843-4b70-8f17-aae3a1aab1c5)

    - Change the order of some items (click on handle to activate , then click and drag to new location).
    - Return to the benefit search page and confirm your new order is reflected in the search results. May need a cache refresh to get the latest json file for search order.

- Spanish benefit finder page should have a similar local task that goes to `/admin/manage-benefits-search-sort/en` and affects the order of search results in the same way as above.
- Confirm the local task does not show up on other pages.
- Confirm the local task shows up if you're logged in as a Content Administrator or Site Admin
- Confirm the local task does not show up for other roles.

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-10-17 02:00 UTC, akf requested changes
It looks good but I'd recommend we wait until after tomorrow's push to staging to merge it, so the content team (okay, Shoshana) can give it a thorough look. 

Also, I don't think we want verbose logging, unless I've missed something. (Even though the cms isn't meant to be for the public, it is exposed.)

2024-10-17 02:00 UTC, akf commented on config/sync/system.logging.yml
Was this just for testing, by chance?

2024-10-17 13:34 UTC, omerida commented
yes, that was for testing, I kept unstaging it but I missed it in the end

On Wed, Oct 16, 2024 at 10:00 PM A.K. Farrell ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> It looks good but I'd recommend we wait until after tomorrow's push to
> staging to merge it, so the content team (okay, Shoshana) can give it a
> thorough look.
>
> Also, I don't think we want verbose logging, unless I've missed something.
> (Even though the cms isn't meant to be for the public, it is exposed.)
> ------------------------------
>
> On config/sync/system.logging.yml
> <https://github.com/usagov/usagov-2021/pull/2013#discussion_r1803996395>:
>
> Was this just for testing, by chance?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/usagov/usagov-2021/pull/2013#pullrequestreview-2373976762>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADYSHTXRAFSGKKLTTNLLJ3Z34K4LAVCNFSM6AAAAABQCGK6OOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZTHE3TMNZWGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-17 13:36 UTC, omerida commented on config/sync/system.logging.yml
Fixed. I kept getting a WSOD with the local tasks

2024-10-24 22:08 UTC, akf approved these changes

2024-10-24 22:08 UTC, merged