USAGOV-1927: Timeouts when updating English or Spanish menus
usagov/usagov-2021 pull request #2035
Opened 2024-10-23 19:49 UTC by DaleMHFrey

https://cm-jira.usa.gov/browse/USAGOV-1927

## Description
Increased the timeouts for the WAF, WWW, and CMS. Kept the WAF value higher than the others.
Added in a little utility to make a page wait/sleep in order to test timeout situations on dev/test (or I may remove this from the PR if this is not necessary).

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [x] Infrastructure
  - [x] CMS
  - [x] WAF
  - [x] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [ ] Other

## Testing Instructions
After this is deployed to Dev/Test we should (if we still have the wait-tool in place) be able to go to /site-lag-test?wait=90 which should take around 90 seconds to load. We can play around with the value, but if we go to a long wait-time like /site-lag-test?wait=130 then we should in theory get a Drupal-error page instead of a nging error-page.

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-10-24 01:05 UTC, akf requested changes
This looks good. I'd feel better if the site_lag_test page were restricted, so we're not opening up a way for just anyone to tie up our server with long-running requests. That's the only thing I'd change!

2024-10-24 01:05 UTC, akf commented on web/modules/custom/usagov_ssg_postprocessing/usagov_ssg_postprocessing.routing.yml
> +    _permission: 'access content'
Please change this to 'access administration pages'

2024-11-07 17:40 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/usagov_ssg_postprocessing.routing.yml
> +    _permission: 'access content'
Ah, this makes sense - this is now updated.

2024-11-07 17:48 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/usagov_ssg_postprocessing.routing.yml
> +    _permission: 'access content'
Oh, hmm, I may not be as familiar with our workflow here. I previously clicked the "Resolve conversation button", but now I am assuming that perhaps that is something that Amy does and I instead am supposed to request a re-review? Let me know if I am doing this right.

2024-11-07 18:23 UTC, akf approved these changes

2024-11-07 18:23 UTC, merged