USAGOV-2020-CEO-A11Y: Update _uswds-theme-custom-styles.scss
usagov/usagov-2021 pull request #2043
Opened 2024-10-28 20:21 UTC by IsabelLaurenceau

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-2020

## Description

Add padding between error bars and ceo fields. 

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [ ] Other

## Testing Instructions

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- At /elected-officials click Find my elected officials (or at es/funcionarios-electos click Encontrar a mis funcionarios electos) 
- When the error bar shows on the left make sure there is 1rem gap
- See these photos for example: 

![after](https://github.com/user-attachments/assets/71bbfffc-4b71-4b12-a20f-e34ffeb5c6bb)
![before](https://github.com/user-attachments/assets/09c525bc-f432-4f12-b94c-05d0f60a7d11)

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-11-01 21:10 UTC, omerida requested changes

2024-11-01 21:10 UTC, omerida commented on web/themes/custom/usagov/sass/_uswds-theme-custom-styles.scss
> +    padding-left: 1rem;
I'm reviewing this and it works if you leave all the fields empty. If I fill in just one field and see this:

![image](https://github.com/user-attachments/assets/ba7cceba-3c72-4560-ad50-7303e3e12ef7)

It looks like in that case `div#error-border` isn't getting this error class applied.

2024-11-01 21:10 UTC, omerida commented on web/themes/custom/usagov/sass/_uswds-theme-custom-styles.scss
> +    padding-left: 1rem;
might be more work to make them consistent, but check out how errors are marked on`/site-issue-report-form`. The error line has the correct padding but does not look like a single connected line

2024-11-04 13:23 UTC, IsabelLaurenceau commented
Good catch! I updated it to use the same class in the javascript as the one in /site-issue-report-form and removed the extra sass

2024-11-04 15:26 UTC, omerida approved these changes

2024-11-04 15:27 UTC, merged