Usagov 2073 published pages
usagov/usagov-2021 pull request #2107
Opened 2024-12-05 04:38 UTC by omerida

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-2073

## Description

Moves generation of the published pages CSV out of the tome export to a drush command that can be executed once the export completes.

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [x] Other

## Testing Instructions

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- On dev branch, run tome export and save published-pages.csv as published-pages-good.csv
- Switch to this branch, run tome export. Compare generated published-pages.csv to good branch above. I do this by sorting the files so they have things in the same order (by path and then node id should work), then using a diff tool to compare them.

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-12-12 00:27 UTC, akf requested changes
I found a couple of things. In addition to the couple of items I marked inline, I'm seeing: 
- Differences in the federal_directory_record titles. We compose the title we put in the HTML from the page title plus the acronym in parenthesis, for example "Administration for Children and Families (ACF)". I'm not 100% sure this is a requirement from the Analytics team's point of view (they are the real customer of this report), but it might be. 
- There are also title discrepancies in some of the Wizard pages. For example term 63, where I'm seeing "Su identidad o la de otra persona" in this version of the report and "¿El estafador usó su identidad o se hizo pasar por alguien?" in the dev version. The dev version does reflect what is in the HTML page. It seems that's coming from the Page Title field, which is not a required field, rather than the Name field, which is (and is what you probably expected). 

That Wizard title discrepancy might point to a need to make another field "required" when editing wizard terms, or it might be that we use the Page Title if it exists and otherwise fall back to Name. I didn't look into that. 

I haven't fully reviewed a couple of the files yet, but this is some actionable feedback. 

It is noticeably faster to do the report this way!

2024-12-12 00:27 UTC, akf commented on web/modules/custom/usagov_benefit_category_search/src/EventSubscriber/DatalayerAlterSubscriber.php
> +    if (!isset($event->datalayer['nodeID']) || !is_numeric($event->datalayer['nodeID'])) {
Is this because the nodeID will not be numeric if it's for a taxonomy page? (If so, I think a comment here would be appropriate.)

2024-12-12 00:27 UTC, akf commented on web/modules/custom/usagov_ssg_postprocessing/src/Data/PublishedPagesRow.php
> +    public readonly string $taxonomyText1,
I always warn people that the "taxonomy" terms in this report are not Drupal Taxonomy, so I think a comment to that effect would be worthwhile: 

// "Taxonomy" in this report reflects the menu structure of the site (for nodes, this is strictly menu-based)

At this moment, I forget what would be accurate to say about the "wizard" taxonomy terms in this case. Don't sweat it if it's complicated to explain.

2024-12-12 00:27 UTC, akf commented on scripts/tome-static.sh
> +  time drush usapubcsv modules/custom/usagov_ssg_postprocessing/files/published-pages.csv
This call needs `--uri=$URI` (I got "http://default" in my report, which messed with my diffs!)

2024-12-16 22:26 UTC, omerida commented
@akf I've updated to add the comments, include the agency acronym with title, and to use the right title fields for wizard terms. Wizards's use a "heading" field for the on page H1, and fall back to the taxonomy name if it's not set.

2024-12-17 00:32 UTC, akf approved these changes, later dismissed
Excellent! The only difference this made in the output is that the "Categories" column in the report has a heading, and you've stripped trailing spaces off of some fields, both of which are improvements. 

There's a lint complaint preventing me from merging this: 

```
FILE: .../custom/usagov_ssg_postprocessing/src/Data/PublishedPagesRow.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 180 | ERROR | [x] Expected newline after closing brace
     |       |     (Drupal.ControlStructures.ControlSignature.NewlineAfterCloseBrace)
```

So please update that!

2024-12-17 14:46 UTC, omerida commented
sorry about that. I've added a local pre-push git hook to check my code style.

2024-12-17 17:25 UTC, akf approved these changes

2024-12-17 17:27 UTC, merged