Usagov 2122 update custom code
usagov/usagov-2021 pull request #2126
Opened 2024-12-18 16:39 UTC by whitealbum

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-2122

## Description

Added to ability to check for PHP8.3 issues

## Type of Changes

- [ ] New Feature
- [x] Bugfix
- [ ] Frontend (Twig, Sass, JS)
  - Add screenshot showing what it should look like
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [ ] Other

## Testing Instructions

run `bin/composer php-compatibility`

### Change Requirements

- [ ] Requires New Documentation (Link: {})
- [ ] Requires New Config
- [ ] Requires New Content

### Validation Steps

- Test instruction 1
- Test instruction 2
- Test instruction 3

## Security Review

- [ ] Adds/updates software (including a library or Drupal module)
- [ ] Communication with external service
- [ ] Changes permissions or workflow
- [ ] Requires SSPP updates

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-12-21 01:21 UTC, akf reviewed
Seems good to me! I flagged Gene on one benefits-finder file, so I'm not merging just yet.

2024-12-21 01:21 UTC, akf commented on web/modules/custom/usagov_benefit_finder/src/Form/BenefitFinderSettingsForm.php
@gchi25 Note that this PR will add an attribute to two functions here. 

I expect that will be acceptable, but I'm going to hold off on approving this for a bit.

2024-12-27 20:28 UTC, akf commented
Heads up, there's a merge conflict now.

2025-01-06 23:38 UTC, gchi25 commented on web/modules/custom/usagov_benefit_finder/src/Form/BenefitFinderSettingsForm.php
@akf Acceptable

2025-01-08 02:50 UTC, akf commented
@whitealbum Gene and I are both happy with this, but now it has merge conflicts. Could you please update?

2025-01-10 15:38 UTC, whitealbum commented on web/modules/custom/usagov_benefit_finder/src/Form/BenefitFinderSettingsForm.php
Merge conflicts handled but the changes to the composer files were extensive so composer things should be rechecked.

2025-01-10 20:33 UTC, akf requested changes
Taking your note about the composer merge to heart, I tore down my site and tried to do a full rebuild via `bin/init`. I'm hitting a couple of issues with `composer install`: 

 - a warning that my composer.lock file is out of date. Usually when we've merged this just means that the content-hash value needs to be updated, and running `composer update --lock` will take care of it
 - a full-blown error: 
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required (in require-dev) package "rector/rector" is not present in the lock file.
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r 
```

That says "warning" but my build failed at that point.

2025-01-10 21:09 UTC, akf reviewed
Confirming that the current version of this branch builds successfully for me. (Unfortunately another merge round is needed.)

2025-01-10 21:28 UTC, akf approved these changes
All working now.

2025-01-10 21:28 UTC, merged