USAGOV-2104: USAGOV-2104 Changes to the updated Published Pages Report
usagov/usagov-2021 pull request #2133
Opened 2024-12-19 17:59 UTC by DaleMHFrey

Some small changes to the updated Published Pages Report

https://cm-jira.usa.gov/browse/USAGOV-2104

## Description
Altering the output of the CSV by creating a wrapper to calls to `fputcsv()`

## Type of Changes

- [ ] New Feature
- [ ] Bugfix
- [ ] Frontend (Twig, Sass, JS)
- [ ] Drupal Config (requires "drush cim")
- [ ] New Modules (requires rebuild)
- [ ] Documentation
- [ ] Infrastructure
  - [ ] CMS
  - [ ] WAF
  - [ ] WWW
  - [ ] Egress
  - [ ] Tools
  - [ ] Cron
- [x] Other

## Testing Instructions
witch to this branch and run the `bin/static-site` script. Then check the file at `web/modules/custom/usagov_ssg_postprocessing/files/published-pages.csv` and expect to see the changes mentioned on the ticket applied.

## Reviewer Reminders

- Reviewed code changes
- Reviewed functionality
- Security review complete or not required

## Post PR Approval Instructions

Follow these steps as soon as you merge the new changes.

1. Go to the [USAGov Circle CI project](https://app.circleci.com/pipelines/github/usagov/usagov-2021).
2. Find the commit of this pull request.
3. Build and deploy the changes.
4. Update the Jira ticket by changing the ticket status to `Review in Test` and add a comment. State whether the change is already visible on [cms-dev.usa.gov](http://cms-dev.usa.gov/) and [beta-dev.usa.gov](http://beta-dev.usa.gov/), or if the deployment is still in process.

2024-12-19 18:50 UTC, omerida requested changes

2024-12-19 18:50 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    unset($rows[20]);
Since we're getting rid of this row, just remove the matching property from the `PublishedPagesRow` class. You'll have to remove it from `__construct()` and then from the factory methods `datalayerForNode()` and `dataLayerForWizard()`

2024-12-19 18:50 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    }
If they want the the language column to use `"Home"` and `"USAGov en Español"` to match the datalayer labels, can replace the `self::getTaxLevel1()` calls in the factory methods with `$data['Taxonomy_Text_1']`.

2024-12-19 18:50 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    unset($rows[2]);
Same as with the header row, remove the Content Type and PageSub typs properties from `PublishedPagesRow` and references to them.

2024-12-19 18:50 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    }
If this is to insure the `hasBenefitCategory` and `benefitCategories` output something ... you should be able to do that by changing `PublishedPagesRow::toArray()` with:

```
this->hasBenefitCategory ?? ' ';
```

and

```
    if ($this->hasBenefitCategory !== "") {
      $array[] = $this->benefitCategories ?: ' ' ;
    }
```

2024-12-19 18:50 UTC, omerida commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +  protected function alter_and_fputcsv($out, $rows) {
I don't see the need for this method. `src/data/PublishedPagesRow` is there to handle what columns get shown, and how they're output. That way, this `publishedCsv()` function doesn't have to know/care/handle anything related to preparing a row for output to the CSV. It just gets the row in line 135, 147, or 170 and can just write it to the CSV file without doing anything else. Notes on how to update the data class follow.

2024-12-30 19:21 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    unset($rows[20]);
ah ok, this is now fixed

2024-12-30 19:21 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    }
ah ok, this is now fixed

2024-12-30 19:22 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    unset($rows[2]);
ah ok, this is now fixed

2024-12-30 19:22 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +    }
ah ok, this is now fixed

2024-12-30 19:22 UTC, DaleMHFrey commented on web/modules/custom/usagov_ssg_postprocessing/src/Drush/Commands/PublishedPagesCommands.php
> +  protected function alter_and_fputcsv($out, $rows) {
ah ok, this is now fixed

2024-12-31 20:18 UTC, omerida submitted a review, later dismissed

2024-12-31 20:19 UTC, omerida commented
@DaleMHFrey Works as advertised but code style linter is failing.

2025-01-02 21:24 UTC, omerida approved these changes

2025-01-02 21:26 UTC, merged