Usagov 257 permission for content editor role
usagov/usagov-2021 pull request #289
Opened 2022-04-29 13:14 UTC by oadekoya12

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-

## Description

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2022-05-03 14:00 UTC, ednark requested changes

2022-05-03 14:00 UTC, ednark commented on web/modules/custom/usa_workflow/usa_workflow.module
> +    dpm($wfusers['currentUser']['usadeleteowncontent'] == FALSE);
Remove debug dpm() statements

2022-05-03 14:00 UTC, ednark commented on web/modules/custom/usa_workflow/usa_workflow.module
> +    if (isset($form['actions'])) {
It looks like this should be wrapped in a 'usadeleteowncontent' check like the other function

2022-05-03 18:34 UTC, oadekoya12 commented on web/modules/custom/usa_workflow/usa_workflow.module
> +    if (isset($form['actions'])) {
ok I will do that now

2022-05-03 18:34 UTC, ednark commented on web/modules/custom/usa_workflow/usa_workflow.module
> +    if (isset($form['actions'])) {
This current logic is wrong. It is removing Deletion capability based off the Approval permission and not the Deletion permission. Please update the logic to something like this

`  if ((in_array($form_id, $newform) || $wfusers['currentUser']['id'] === $wfusers['reviseduser']['id']) {
    if ($wfusers['currentUser']['usaapproveowncontent'] === FALSE) {
      unset($form['moderation_state']['widget'][0]['state']['#options']['published']);
      if (isset($form['new_state'])) {
        unset($form['new_state']['#options']['published']);
    }
    if (isset($form['actions']) 
        && $wfusers['currentUser']['usadeleteowncontent'] === FALSE) {
      unset($form['actions']['delete']);
    }
  }`

2022-05-04 18:26 UTC, oadekoya12 commented on web/modules/custom/usa_workflow/usa_workflow.module
> +    if (isset($form['actions'])) {
Done

2022-05-04 18:59 UTC, ednark approved these changes

2022-05-04 18:59 UTC, merged