Update README
usagov/usagov-2021 pull request #346
Opened 2022-06-16 17:41 UTC by thetypicalprogrammer

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-

## Description

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2022-06-17 13:32 UTC, ednark requested changes
I think the rest of your comments are very helpful in clarifying things.

2022-06-17 13:32 UTC, ednark commented on README.md
> +4. Run the following command:
Steps 3-5  should  be unnecessary.  db-update runs inside the database container started in step 1, and drupal-update actually asks composer to start up totally new containers to handle each step. So stopping and starting composer shouldn't do anything. I think maybe it was left at the bottom as a mistake

2022-06-17 13:44 UTC, thetypicalprogrammer commented on README.md
> +4. Run the following command:
That makes sense. I left in Step 5 (now step 2) just to make it clear where to view the page once the container is running.

2022-06-21 14:25 UTC, ednark submitted a review, later dismissed

2022-06-21 14:48 UTC, ednark approved these changes

2022-06-21 14:49 UTC, merged