Usagov 430 spanish directories
usagov/usagov-2021 pull request #573
Opened 2022-11-28 16:02 UTC by IsabelLaurenceau

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-403

## Description

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2022-11-29 20:01 UTC, akf requested changes
I have a change request to your setup, which will require adjustment (probably to the block layout): 
The basic page "Agencias federales" should have: 
*  "Español" selected for language
* URL alias entered as simply "/indice-agencias" 
Our Drupal setup automatically prepends "/es" to the paths of Spanish-language pages, so if I follow your directions and choose Español, I get a page at /es/es/indice-agencias. If I don't choose Español, other things are wrong. If I choose Español and enter /indice-agencias, the page at /es/indice-agencias doesn't have the index on it.

2022-11-29 20:01 UTC, akf commented on web/themes/custom/usagov/templates/views-view-fields--federal-agencies.html.twig
> +      <div>
Nice! Glad to have this text out of the view and into a twig file.

2022-11-30 16:12 UTC, IsabelLaurenceau commented
> I have a change request to your setup, which will require adjustment (probably to the block layout): The basic page "Agencias federales" should have:
> 
> * "Español" selected for language
> * URL alias entered as simply "/indice-agencias"
>   Our Drupal setup automatically prepends "/es" to the paths of Spanish-language pages, so if I follow your directions and choose Español, I get a page at /es/es/indice-agencias. If I don't choose Español, other things are wrong. If I choose Español and enter /indice-agencias, the page at /es/indice-agencias doesn't have the index on it.

Ah okay, I did not know that Drupal did that for us! And you were right the only change needed was in the block layout.

2022-11-30 17:50 UTC, akf approved these changes

2022-11-30 17:50 UTC, akf commented
Looks good! I realized we will also want to add the menu link, so I added that to the testing instructions in the ticket.

2022-11-30 17:51 UTC, merged