usagov-617-Put-an-attribute-with-the-originating-Node-ID-within-each-…
usagov/usagov-2021 pull request #617
Opened 2022-12-23 12:55 UTC by sinchagrenchik

…agency-accordion-on-the-A-to-Z-Letter-pages: Update views-view-fields--federal-agencies.html.twig

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-617

## Description

## Checklist for the Developer

- [x ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [x ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2022-12-23 13:24 UTC, IsabelLaurenceau requested changes

2022-12-23 13:24 UTC, IsabelLaurenceau commented on web/themes/custom/usagov/templates/views-view-fields--federal-agencies.html.twig
> +{% set Title = 'dr-' ~ fields.title.content|striptags|trim %}
Can we change this to 
{% set UTitle = 'dr-' ~ fields.title.content|striptags|trim %}

2022-12-23 13:24 UTC, IsabelLaurenceau commented on web/themes/custom/usagov/templates/views-view-fields--federal-agencies.html.twig
> +{% set Title = 'dr-' ~ fields.title.content|striptags|trim %}
Button needs to be changed to still use UTitle and set UID in data attribute
```
  <button
      aria-controls="{{- UTitle -}}"
      data-node-id="{{- UID -}}
      aria-expanded="false"
      class="usa-accordion__button"
      >
```

2022-12-23 13:24 UTC, IsabelLaurenceau commented on web/themes/custom/usagov/templates/views-view-fields--federal-agencies.html.twig
> +{% set Title = 'dr-' ~ fields.title.content|striptags|trim %}
Div on line 54 needs to be changed to 
`<div class="usa-accordion__content usa-prose" id="{{- UTitle -}}" data-node-id="{{- UID -}}">
`

2023-01-03 23:23 UTC, akf commented
I'm picking this one up and starting a new branch from the current dev branch.

2023-01-03 23:23 UTC, closed without merging