USAGOV-725-alt-text-homepage: Alt Text
usagov/usagov-2021 pull request #676
Opened 2023-02-08 16:24 UTC by IsabelLaurenceau

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-725

## Description

Alt text should be available for all images on homepage

## Checklist for the Developer

- [x] A link to the JIRA ticket has been added above.
- [x] The JIRA ticket identifies the desired result of this change.
- [x] The JIRA ticket contains clear acceptance criteria.
- [x] The JIRA ticket contains clear testing steps.
- [x] The JIRA ticket contains a description of "Done".
- [x] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2023-02-08 22:58 UTC, akf requested changes
The only problem I see is that the alt text for the Life Events images is missing quotation marks.

2023-02-08 22:58 UTC, akf commented on web/themes/custom/usagov/templates/views-view-fields--life-events-view.html.twig
> +		<img class="thumbnailBanner" alt={{image_card_alt}} src={{file_url(image_card_uri|image_style('max_480w'))}}/>
The alt text here needs quotation marks around it.

2023-02-09 15:07 UTC, msvgsa commented
Reviewed and appears to be working:

![USAGOV-725-Test-001](https://user-images.githubusercontent.com/111382438/217850731-d60bc4ac-4dc7-439e-a438-352103d815c1.png)

2023-02-09 15:07 UTC, msvgsa approved these changes
Tested and working in local env.

2023-02-09 15:10 UTC, ghost commented on web/themes/custom/usagov/templates/views-view-fields--life-events-view.html.twig
> +		<img class="thumbnailBanner" alt={{image_card_alt}} src={{file_url(image_card_uri|image_style('max_480w'))}}/>
I tested this yesterday, and it appear to add the quotes - see screenshot.

2023-02-09 16:10 UTC, merged