USAGOV-866-update-tome-for-cutover: changed tome to reference www # Please enter the commit message for your changes. Lines starting # with '#' will be ignored, and an empty message aborts the commit. # # On branch USAGOV-866-update-tome-for-cutover # Changes to be committed: # modified: scripts/tome-run.sh # modified: scripts/tome-static.sh #
usagov/usagov-2021 pull request #817
Opened 2023-04-04 21:28 UTC by jacobaaronyeager

## Jira Task

https://cm-jira.usa.gov/browse/USAGOV-866

## Description

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been added above.
- [ ] The JIRA ticket identifies the desired result of this change.
- [ ] The JIRA ticket contains clear acceptance criteria.
- [ ] The JIRA ticket contains clear testing steps.
- [ ] The JIRA ticket contains a description of "Done".
- [ ] Any preparation/installation/update steps required for this code to work properly (drush commands, scripts, configuration updates) are documented in the ticket.

## Checklist for the Peer Reviewers
- [ ] The branch name of this PR matches the project standards.
- [ ] QA steps are followed and any changes to process are updated in the ticket.
- [ ] Code Standards are followed, there are no bad practices in use.
- [ ] Config changes (if any) include only necessary changes.
- [ ] No errors in Drupal or Client Browser.
- [ ] Code has been tested locally (if possible).
- [ ] Following AC and Testing Steps verify changes work as expected.
- [ ] There are no known side-effects outside of expected behavior.

2023-04-04 23:04 UTC, akf requested changes
I forgot a piece here, which is why this turned out to be so small. 

/etc/periodic/15min/generate-static-site (in .docker/src-cms) needs an update too. If we can verify that ${WWW_HOST} will have the right thing in it, we can use that and merge this in before cutover. If that's a problem, we should change it to www.usa.gov and ... I'm not sure about merging it before cutover. I'm going to ask the analytics team if that would be bad. 

So I think the more interesting task here is looking into whether we have WWW_HOST getting populated correctly for this. Take a look at the change I made to scripts/bootstrap.sh on https://github.com/usagov/usagov-2021/pull/797/files

I'm going to close that pull request (since I took the other approach with nginx config), but that bit about setting WWW_HOST to either www or beta (not both) is probably valid here.

2023-04-05 03:10 UTC, akf commented
Update to my last comment -- I just confirmed with DK that as far as he knows, it would be fine for us to have "www.usa.gov" showing up in things like canonical URLs on beta.usa.gov, as long as beta's putting out the "noindex" header (which it is). So I think we can make this whole thing a lot easier on ourselves by starting to generate the static site pages with "www.usa.gov" at any point now. Then we don't need to worry about how long it might take to get it updated on cutover day.

2023-04-05 17:50 UTC, msvgsa approved these changes, later dismissed

2023-04-05 19:11 UTC, akf approved these changes

2023-04-05 19:11 UTC, merged